[tool.poetry]
name = "makefile-demo"
version = "0.1.0"
description = ""
authors = ["gdhoot <gdhoot202@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
certifi = "^2024.2.2"
charset-normalizer = "3.3.2"
idna = "^3.7"
urllib3 = "^2.2.1"
